FROM node:24-slim AS builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

FROM node:24-slim AS runner
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY ./vite.config.js ./vite.config.js
RUN npm install --save-dev vite @vitejs/plugin-react vite-plugin-node-polyfills

EXPOSE 4173
CMD ["npx", "vite", "preview"]