services:
  frontend:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - ./frontend/src/contracts.ts:/app/src/contracts.ts
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
  hardhat_forked:
    profiles:
      - forked
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - SEPOLIA_RPC_URL
      - SEPOLIA_PRIVATE_KEY
    volumes:
      - ./blockchain:/app
    ports:
      - "8545:8545"
    command: sh -c "npm install && npx hardhat node --network local_sepolia_fork"
  hardhat_mocked:
    profiles:
      - mocked
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - SEPOLIA_RPC_URL
      - SEPOLIA_PRIVATE_KEY
    volumes:
      - ./blockchain:/app
    ports:
      - "8545:8545"
    command: sh -c "npm install && npx hardhat node"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - FORUM_CONTRACT_ADDRESS
    volumes:
      - ./backend:/app
    command: sh -c "
      source .venv/bin/activate
      && python -m pip install uv
      && python -m uv pip sync requirements.txt
      && python src/ourvoice/main.py --forum-contract-address ${FORUM_CONTRACT_ADDRESS} --ethereum-node-url ws://hardhat_mocked:8545"