services:
  hardhat_forked:
    profiles:
      - forked
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - SEPOLIA_RPC_URL
      - SEPOLIA_PRIVATE_KEY
    volumes:
      - ./blockchain:/app
    ports:
      - "8545:8545"
    command: sh -c "npm install && npx hardhat node --network local_sepolia_fork"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 30s
      retries: 3
      timeout: 2s
      start_period: 2m
      # start_interval: 5s
  hardhat_mocked:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./blockchain:/app
    ports:
      - "8545:8545"
    command: sh -c "npm install && npx hardhat node"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 30s
      retries: 3
      timeout: 2s
      start_period: 2m
      # start_interval: 5s
  contract_deployer:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./blockchain:/app
      - ./frontend:/frontend
    environment:
      - DEPLOY_MODE=mock
    depends_on:
      hardhat_mocked:
        condition: service_healthy
    command: sh -c "
      npm install
      && rm -rf ignition/deployments/chain-31337
      && npx hardhat clean
      && npx hardhat compile
      && npx hardhat run scripts/deploy.ts --network compose_hardhat"
  frontend:
    profiles:
      - dev
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - ./frontend/src/contracts.ts:/app/src/contracts.ts
    ports:
      - "5173:5173"
    depends_on:
      hardhat_mocked:
        condition: service_healthy
    command: sh -c "npm install && npm run dev -- --host"
  frontend_preview:
    profiles:
      - preview
    image: ghcr.io/ourvoice/ourvoice-site-preview:${PR_TAG}
    ports:
      - "4173:4173"
  zoo:
    image: zookeeper:3.9
    environment:
      ZOO_4LW_COMMANDS_WHITELIST: "mntr,conf,ruok"
  solr:
    image: solr:9-slim
    ports:
      - "8983:8983"
    environment:
      ZK_HOST: "zoo:2181"
    depends_on: [zoo]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/"]
      interval: 30s
      retries: 3
      timeout: 2s
      start_period: 30s
      # start_interval: 5s
  solr_setup:
    image: curlimages/curl:latest
    depends_on:
      solr:
        condition: service_healthy
    restart: "no"
    command:
      - sh
      - '-c'
      - >-
        curl --request POST
        --url http://solr:8983/api/collections
        --header 'Content-Type: application/json'
        --data '{"name": "ourvoice", "numShards": 1, "replicationFactor": 1}' &&
        curl --request POST
        --url http://solr:8983/api/collections/ourvoice/schema
        --header 'Content-Type: application/json'
        --data @/data/ourvoice-solr-schema.json
    volumes:
      - ./backend/ourvoice-solr-schema.json:/data/ourvoice-solr-schema.json:ro
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - FORUM_CONTRACT_ADDRESS=${FORUM_CONTRACT_ADDRESS:-0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0}
    volumes:
      - ./backend:/app
    depends_on:
      contract_deployer:
        condition: service_completed_successfully
    command: sh -c "
      python -m venv .venv || true
      && source .venv/bin/activate
      && python -m pip install uv
      && python -m uv pip sync requirements.txt
      && python src/ourvoice/main.py \
          --forum-contract-address '${FORUM_CONTRACT_ADDRESS}' \
          --ethereum-node-url ws://hardhat_mocked:8545 \
          --solr-url http://solr:8983/solr/ourvoice"
  backend_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - SOLR_URL=http://solr:8983/solr/ourvoice
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      solr_setup:
        condition: service_completed_successfully
      contract_deployer:
        condition: service_completed_successfully
    command: sh -c "
      python -m venv .venv || true
      && source .venv/bin/activate
      && python -m pip install uv
      && python -m uv pip sync requirements.txt
      && fastapi run src/ourvoice/search_service/main.py"
