services:
  frontend:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - ./frontend/src/contracts.ts:/app/src/contracts.ts
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
  hardhat_fork:
    profiles:
      - hardhat-fork
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - SEPOLIA_RPC_URL
      - SEPOLIA_PRIVATE_KEY
    volumes:
      - ./blockchain:/app
    ports:
      - "8545:8545"
    command: sh -c "npm install && npx hardhat node --network local_sepolia_fork"
  hardhat_mock:
    profiles:
      - hardhat-mock
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - SEPOLIA_RPC_URL
      - SEPOLIA_PRIVATE_KEY
    volumes:
      - ./blockchain:/app
    ports:
      - "8545:8545"
    command: sh -c "npm install && npx hardhat node"