#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# Waits for Hardhat + Meilisearch, then starts the backend (uvicorn).
#
# The FORUM_CONTRACT_ADDRESS is extracted from the deployed frontend network
# config file generated by deploy.ts.
#
# Usage (called by overmind via Procfile, not directly):
#   DEPLOY_NETWORK=default \
#     scripts/local-backend.sh
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

HARDHAT_URL="${HARDHAT_URL:-http://127.0.0.1:8545}"
MEILI_URL="${MEILI_URL:-http://localhost:7700}"
NETWORK_FILE_NAME="${NETWORK_FILE_NAME:-localhost}"

echo "⏳ Waiting for Hardhat node at ${HARDHAT_URL}…"
until curl -sf "${HARDHAT_URL}" > /dev/null 2>&1; do
  sleep 1
done

echo "⏳ Waiting for Meilisearch at ${MEILI_URL}…"
until curl -sf "${MEILI_URL}/health" > /dev/null 2>&1; do
  sleep 1
done

# Wait for the deploy script to write the network config file.
NETWORK_CONFIG="frontend/src/contracts/networks/${NETWORK_FILE_NAME}.ts"
echo "⏳ Waiting for contract deployment (${NETWORK_CONFIG})…"
until [ -f "${NETWORK_CONFIG}" ]; do
  sleep 2
done
# Give deploy.ts a moment to finish writing.
sleep 2

# Extract the first Forum address from the generated TS file.
# The file contains: export const FORUMS = { "global": "0x...", ... }
FORUM_ADDRESS=$(grep -oE '0x[0-9a-fA-F]{40}' "${NETWORK_CONFIG}" | head -1)
if [ -z "${FORUM_ADDRESS}" ]; then
  echo "❌ Could not extract FORUM_CONTRACT_ADDRESS from ${NETWORK_CONFIG}"
  exit 1
fi
echo "📋 Using FORUM_CONTRACT_ADDRESS=${FORUM_ADDRESS}"

export FORUM_CONTRACT_ADDRESS="${FORUM_ADDRESS}"
export ETHEREUM_NODE_URL="${ETHEREUM_NODE_URL:-ws://127.0.0.1:8545}"
export MEILI_URL
export MEILI_API_KEY="${MEILI_API_KEY:-dev-master-key}"
export BACKFILL_FROM="${BACKFILL_FROM:-all}"
export CORS_ORIGINS="${CORS_ORIGINS:-*}"

cd backend
# Activate venv if it exists; otherwise expect system Python has deps.
if [ -f .venv/bin/activate ]; then
  # shellcheck disable=SC1091
  . .venv/bin/activate
fi

exec uvicorn ourvoice.combined:app --host 127.0.0.1 --port 8000 --app-dir src
