/**
 * Contract addresses for the base_sepolia network with MockSymvoliaRegistry.
 * Auto-generated by `scripts/generate-deployment-artifacts.mjs` -- do not edit manually.
 */

export const FORUMS = {
  "global": "0x748ace05A49A04f067469C61F18a6A2Ec55E75e5",
  "USA": "0xfba9317B2bA87c2E7Fcdf59f884aF8eAfEB02961",
  "CAN": "0x1a99FbD23261a4E62532B44beb830e5cA281d9e6"
} as const;

export const REGISTRY_ADDRESS = "0x3c4d6d6199d35410399588223B61aF31D1F058C4" as const;
