/**
 * Contract addresses for the base_sepolia network with MockSymvoliaRegistry.
 * Auto-generated by `scripts/generate-deployment-artifacts.mjs` -- do not edit manually.
 */

export const FORUMS = {
  "global": "0x70D8D0Fb592d9344a99E1b4945aFCC24df6a6b0e",
  "USA": "0xDa20482524524FaAe3A199A18922d1ecb9b20A9A",
  "CAN": "0xCE54d3a4824d8f5945b4797d4Aa399ACe91D107b"
} as const;

export const REGISTRY_ADDRESS = "0x5e3F15199b88A3497cc7510ffb7A429D0Cf4dB19" as const;
