/**
 * Contract addresses for the base_sepolia network with DevSymvoliaRegistry.
 * Auto-generated by `scripts/generate-deployment-artifacts.mjs` -- do not edit manually.
 */

export const FORUMS = {
  "global": "0x97cE3ABDB799413129F6cb3DFCD20F4104c34840",
  "USA": "0x3104efCff9D43be16F74eB649363d2888a91108c",
  "CAN": "0xe02B6D91E7182E9917945703C10d54c9379E1f66"
} as const;

export const REGISTRY_ADDRESS = "0x16CEBcFb37Cb8Ec1D1C2D80596C2131352aa0944" as const;
