/**
 * Contract addresses for the sepolia network.
 * Auto-generated by `scripts/generate-deployment-artifacts.mjs` -- do not edit manually.
 */

export const FORUMS = {
  "global": "0x032166BC380bd06B5805D3AC8fB44139eDe31Aa6",
  "USA": "0x000Fd29478e2F4f7ff02Bb9d5F71791a78859659",
  "CAN": "0x69F68dc0404b523Fc6d8cD9A86Fe147dcc717450"
} as const;

export const REGISTRY_ADDRESS = "0x4d6B0F496C831A0fF4DE3bCF7A7a8675a93Dde9e" as const;
