/**
 * Contract addresses for the Sepolia testnet (chain 11155111).
 * Auto-generated by `blockchain/scripts/deploy.ts` — do not edit manually.
 */

export const FORUMS = {
  global: "0x49b5Cbe5178835350bF65ae4Fb2EB6C400bfD88A",
  us: "0xEc9c3fD9144e899737f90A3E1baA577e2a7048c7",
  zkr: "0x524a0d8221Ea0C91846fe5D2b1DE89c390756E7e",
} as const;

export const REGISTRY_ADDRESS =
  "0x14725fBaD4A976F864f2fEFA4fC224C81cDe022D" as const;
