/**
 * Contract addresses for the sepolia network.
 * Auto-generated by `blockchain/scripts/deploy.ts` — do not edit manually.
 */

export const FORUMS = {
  "global": "0x41700393DCE01EfdBff7E92fa4801AD59a5efBeA",
  "us": "0x742241A01f483b8D7196F3ba73eF231B69b138c6",
  "zkr": "0xa0B568c93F053dC5Cf1d3eF1fC65f1076b4A8179"
} as const;

export const REGISTRY_ADDRESS = "0x97dcc39CB98BDC5cc493f9799a1d01021D2563ED" as const;
