import hre from "hardhat";
import path from "path";
import { mkdirSync, writeFileSync } from "fs";
import { createForumProductionModule } from "../ignition/modules/ForumProduction.js";
import { createForumMockedModule } from "../ignition/modules/ForumMockedRegistry.js";
import { getDeploymentConfig } from "../ignition/config/deployments.js";

/** Minimal contract shape we need for post-deploy output generation. */
type DeployedContract = { address: string; abi: unknown[] };

async function main() {
  const connection = await hre.network.connect();
  const { networkName, ignition } = connection;
  const config = getDeploymentConfig(networkName);

  console.log(
    `Deploying to network "${networkName}" in "${config.mode}" mode…`,
  );
  console.log(`Forums: ${config.forums.join(", ")}`);

  let registry: DeployedContract;
  let forums: Record<string, DeployedContract>;

  // Simulated networks only: advance block timestamp to real time so that
  // time-dependent contract logic (e.g. ZKPassport proof validity windows)
  // behaves realistically during development. Forked networks inherit the
  // timestamp of the pinned block, which can be far in the past.
  if ("networkHelpers" in connection) {
    const { networkHelpers } = connection;
    await networkHelpers.time.increaseTo(Math.floor(Date.now() / 1000) + 1);
  }

  if (config.mode === "mocked") {
    const module = createForumMockedModule(
      config.forums, config.stepDurationSeconds, config.engagementWindowSeconds,
      config.maxRankedStatements, config.minStatementSupportToRank,
      config.maxStatementLength, config.userCreditAllowancePerStep, config.userStartingCredits,
    );
    const deployResult = await ignition.deploy(module);
    ({ registry, ...forums } = deployResult);
  } else {
    const module = createForumProductionModule(
      config.forums, config.stepDurationSeconds, config.engagementWindowSeconds,
      config.maxRankedStatements, config.minStatementSupportToRank,
      config.maxStatementLength, config.userCreditAllowancePerStep, config.userStartingCredits,
    );
    const parametersPath = path.resolve(
      import.meta.dirname,
      "../ignition/parameters",
      config.parametersFile,
    );
    const deployResult = await ignition.deploy(module, {
      parameters: parametersPath,
    });
    ({ registry, ...forums } = deployResult);
  }

  console.log("Deployed OurVoiceRegistry at:", registry.address);
  for (const [name, contract] of Object.entries(forums)) {
    console.log(`Deployed Forum (${name}) at:`, contract.address);
  }

  const forumAddresses = Object.fromEntries(
    Object.entries(forums).map(([name, contract]) => [name, contract.address]),
  );

  // Determine the frontend network file name from the Hardhat network.
  // Mocked-mode deployments always write "localhost"; production-mode
  // deployments use the actual Hardhat network name (e.g. "sepolia").
  // Local native networks (localhost*) also map to "localhost".
  const networkFileName =
    config.mode === "mocked" || networkName.startsWith("localhost")
      ? "localhost"
      : networkName;

  const networksDir = path.resolve(
    import.meta.dirname,
    "../../frontend/src/contracts/networks",
  );
  mkdirSync(networksDir, { recursive: true });

  const label =
    config.mode === "mocked"
      ? "the local Hardhat development network (chain 31337)"
      : `the ${networkName} network`;

  const networksModuleText =
    "/**\n" +
    ` * Contract addresses for ${label}.\n` +
    " * Auto-generated by `blockchain/scripts/deploy.ts` — do not edit manually.\n" +
    " */\n\n" +
    `export const FORUMS = ${JSON.stringify(forumAddresses, null, 2)} as const;\n\n` +
    `export const REGISTRY_ADDRESS = "${registry.address}" as const;\n`;

  const outPath = path.join(networksDir, `${networkFileName}.ts`);
  writeFileSync(outPath, networksModuleText);
  console.log(`Wrote frontend network config to ${outPath}`);

  // Switch from automine to interval mining for development networks.
  // Automine is used during deployment for speed; interval mining (12s)
  // simulates realistic block production for manual interaction afterward.
  if (networkName !== "sepolia") {
    const { provider } = connection;
    await provider.request({ method: "evm_setAutomine", params: [false] });
    await provider.request({
      method: "evm_setIntervalMining",
      params: [12000],
    });
    console.log("Switched to interval mining (12s blocks).");
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
