# .github/workflows/pullpreview.yml
name: PullPreview
on:
  pull_request:
    types: [labeled, unlabeled, synchronize, closed, reopened]

jobs:
  deploy:
    permissions:
      contents: read # to fetch code (actions/checkout)
      deployments: write # to delete deployments
      pull-requests: write # to remove labels
      statuses: write # to create commit status
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: pullpreview/action@v5
      # see https://github.com/pullpreview/action/wiki/Inputs
      with:
        admins: mitrydoug
        compose_files: docker-compose.yml
        # pre_script: ./preview_setup.sh
        default_port: 5173
        ports: 4173,5173,8000,8545
        instance_type: "medium"
        ttl: 12h
      env:
        AWS_ACCESS_KEY_ID: "${{ secrets.PR_AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.PR_AWS_SECRET_ACCESS_KEY }}"
        AWS_REGION: "us-east-1"